# Generated by Django 2.0.2 on 2018-02-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('cibles', models.ManyToManyField(related_name='medicaments', to='homeo.Cible')),
            ],
        ),
        migrations.CreateModel(
            name='ModeReactionnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('yellow', 'Jaune'), ('red', 'Rouge'), ('blue', 'Bleu'), ('green', 'Green')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='medicament',
            name='modes',
            field=models.ManyToManyField(related_name='medicaments', to='homeo.ModeReactionnel'),
        ),
    ]
