# Generated by Django 2.0.2 on 2018-03-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cible',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modereactionnel',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='modes',
            field=models.ManyToManyField(blank=True, related_name='medicaments', to='homeo.ModeReactionnel'),
        ),
        migrations.AlterField(
            model_name='modereactionnel',
            name='color',
            field=models.CharField(choices=[('yellow', 'Jaune'), ('red', 'Rouge'), ('blue', 'Bleu'), ('green', 'Vert')], max_length=10),
        ),
    ]
